# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180421_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
