# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180506_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
