# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 16:05
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Ammar\\Desktop\\ECommerce\\protected/'), upload_to=product.models.product_file_loc),
        ),
    ]
