# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import product.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20180712_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=product.models.product_file_loc),
        ),
    ]
