# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180715_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfile',
            options={},
        ),
    ]
