# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20180715_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfile',
            options={'ordering': ('name', '-created')},
        ),
    ]
