# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
