# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180517_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 9, 17, 15, 47, 192555, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
