# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-updated', '-created')},
        ),
    ]
