# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markting', '0002_marktingprefrence_mailchimp_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marktingprefrence',
            name='mailchimp_msg',
            field=models.TextField(blank=True),
        ),
    ]
